name: Docker Image CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
    - name: Check Out
      uses: actions/checkout@v1
    - name: Build Docker image. Login and push to Docker Hub
      run: |
        docker build . -t ${{ secrets.REPO_TAG }}
        docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }}
        docker push ${{ secrets.REPO_TAG }}
        docker logout
    - name: 'Login via Azure CLI'
      uses: azure/actions/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/webapps-container-deploy@v1
      with:
        app-name: 'github-action-docker'
        images: 'index.docker.io/${{ secrets.REPO_TAG }}'
